### ISSUE TITLE
Would be nice to add some useful things

### ISSUE THREAD

**Issue by jevgenyonegin** [drygdryg/OneShot#23]
1. Show AP as locked (orange, not red) if wps pin already is stored.
2. If is possible to enable refresh scan simple pressing enter. Do not really understand loop option, same moves ctrl+c, key up, enter...
3. Auto add new AP model (if model captured) in vulnerable list on success. (Zyxel nbg-418N is vulnerable, nbg-418N v2 is not)
4. And the most wonderful, ability to add location string (-g option?) on success! Termux-location can provide that. As example: LOC: 56.94600000,24.10589000
Anyway, thanks for keep this project updated.
You are the best!!!

**Comment by drygdryg** [comment]
> Show AP as locked (orange, not red) if wps pin already is stored.

Sorry, at the moment there are 3 colors for highlighting network States, and if you increase their number, there may be a situation when they will not display well on some terminals. I found a compromise: OneShot can highlight the network in yellow if WPS is locked but network is stored.
> If is possible to enable refresh scan simple pressing enter. Do not really understand loop option, same moves ctrl+c, key up, enter...

That's a good idea, thank you. Soon it will be implemented.
> Auto add new AP model (if model captured) in vulnerable list on success. (Zyxel nbg-418N is vulnerable, nbg-418N v2 is not)

Unfortunately, I can't program this behavior because some router models require special attention. In the near future, I plan to improve the storage of vulnerable models by turning it into a database. When I do, I will consider your offer.
> And the most wonderful, ability to add location string (-g option?) on success! Termux-location can provide that. As example: LOC: 56.94600000,24.10589000

OneShot aims to be a universal tool that runs on a wide variety of systems running on the Linux kernel. Therefore, unfortunately, this idea needs to be universalized.

**Comment by eda-abec** [comment]
> enable refresh scan simple pressing enter.

Check #26 

> Auto add new AP model (if model captured) in vulnerable list on success. (Zyxel nbg-418N is vulnerable, nbg-418N v2 is not)

I think semi-automation is feasible without an DB, there could be just switch, which would compare `stored.csv` with `vulnwsc.txt` and print those not in list, one per line, and exit. Then it would be up to user to copy them and assure they aren't already submitted.

> OneShot aims to be a universal tool

Agree. That's why I'm planning it as a separate repository.

**Comment by eda-abec** [comment]
So, I finally made the GPS part working! For sake of keeping OneShot clean of platform-specific code, I decided to use two existing tools and then merge their outputs. You are welcome to take a look [here](https://github.com/eda-abec/OneShot-GPS-Merge).

**Comment by jevgenyonegin** [comment]
Any ideas to integrate somethig like this on success and add values to stored?
>  #!/bin/bash
#pkg install termux-api jq
lat=$(termux-location | jq '.latitude')
lon=$(termux-location | jq '.longitude')
echo "$lat, $lon" >> $"./geo_location.csv"
